Initial Typescript Setup
orbiting/backends pull request #493
Opened 2020-08-21 09:20 UTC by caillou

# Initial Typescript Setup

## Abstract

The aim of this PR is to have a working and deployable TypeScript setup. 

In addition, we would like to experiment with `JS` to `TS` migration. For that purpose, the following file and all it's dependencies should be migrated to TypeScript. The `any` type should be avoided, with the exception if highly generic code.

## Tasks

- [x] Migrate the following files to TS
  - [x] packages/auth/loaders/User.ts
  - [x] packages/auth/lib/transformUser.ts
  - [x] packages/auth/lib/index.ts
  - [x] packages/auth/index.ts
  - [x] packages/dataloader/index.ts
- [x] Set up `TS`:
  - [x] `tsconfig.json`
  - [x] add dependencies 
  - [x] build task with watcher
  - [x] nodemon for dev
- [x] Deployment

2020-08-27 09:15 UTC, tpreusse approved these changes
Looks good 🎉 

One thing: we should add [eslint & prettier](https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project) for tsc files. Currently the style is inconsistent and a few semicolons snuck in. But IMO something for a separate PR.
Would be

2020-08-27 10:40 UTC, patte commented
`yarn run tsc` gives me the following error:
```
yarn run v1.22.4
$ /home/patte/republik/src/backends/node_modules/.bin/tsc
packages/auth/loaders/User.ts:48:15 - error TS1005: ',' expected.

48     credential: createDataLoader(ids =>
                 ~

packages/auth/loaders/User.ts:51:3 - error TS1005: ',' expected.

51   }
     ~


Found 2 errors.
```
Also, could you please add a section to the `README.md` explaining that the project uses typescript, how to run in development, about not to check in generated files and how it's run in prod.

2020-08-29 15:00 UTC, tpreusse requested changes

2020-08-29 15:00 UTC, tpreusse commented on packages/auth/lib/index.ts
> +export default {
I get the following error on staging:
<img width="856" alt="Screenshot 2020-08-29 at 16 56 54" src="https://user-images.githubusercontent.com/410211/91639726-e88eaa80-ea18-11ea-941b-019da4380bf8.png">

Caused by the `revokeConsent` mutation:
https://github.com/orbiting/backends/blob/458cf43e19724854f56b398485475fe8da52786d/packages/auth/graphql/resolvers/_mutations/revokeConsent.js#L1

seems like requiring from this file after changing export style does not work as expected.

2020-09-09 20:12 UTC, philippstucki commented on tsconfig.json
> +    // "strictNullChecks": true, /* Enable strict null checks. */
I highly recommend enabling strict null checks.

2020-09-11 09:11 UTC, caillou commented
@tpreusse ready for review once again.

2020-09-11 15:07 UTC, tpreusse approved these changes

2020-09-11 15:32 UTC, merged