Fix: scheduler with missing credit cards
orbiting/backends pull request #500
Opened 2020-09-02 16:40 UTC by caillou

Todo:

- [x] Fix `membership_owner_autopay_notice`
- [ ] Fix `membership_owner_autopay`

2020-09-02 16:41 UTC, caillou commented
@tpreusse Would you by any chance know, how I can locally test this code?

2020-09-03 06:29 UTC, tpreusse requested changes

2020-09-03 06:29 UTC, tpreusse commented on packages/republik-crowdfundings/lib/scheduler/owners.js
> +  return mailings(user, bucket, context)
(card is expected on `user.autoPay.card` by downstream functions not `user.defaultPaymentSource`, but no longer relevant if we move to `suggest`)

2020-09-04 06:52 UTC, tpreusse reviewed
One more thing ;-)

2020-09-04 14:13 UTC, tpreusse approved these changes

2020-09-04 14:28 UTC, merged

2020-09-04 16:38 UTC, tpreusse commented on packages/republik-crowdfundings/lib/AutoPay.js
> +  const defaultPaymentSource = getDefaultPaymentSource(membership.userId, pgdb)
an await is missing 🙈