Extend membership and revenue stats
orbiting/backends pull request #568
Opened 2021-03-01 13:12 UTC by fuenkchen

Extensions in stats:
- membership: 
  - age distribution of current members
  - first names and sex classification of current members
  - postal codes/countries and top 5 cities/other addresses per year
  - active loyalists and crowdfunders integrated in evolution
- revenue 
  - revenue and sold unit per segment per year

2021-03-02 12:20 UTC, patrickvenetz requested changes
I like what you've done.

2021-03-02 12:20 UTC, patrickvenetz commented on packages/republik/lib/MembershipStats/geo.js
> +    })
```suggestion
    const country = !!membership.country.trim() && countries.find((country) => {
      return (
        country.name === membership.country ||
        country.searchNames.includes(membership.country.toLowerCase().trim())
      )
    })
```

Could be a slight speed improvement: Checking first if country is truthy before digging in countries array.

Do you think `.includes` is faster than `.indexOf`? I find it more readable.

Also, trimming might increase likely-hood of finding a matching country.

2021-03-02 12:20 UTC, patrickvenetz commented on packages/republik/lib/MembershipStats/names.js
> +    ORDER BY 3 DESC
```suggestion
    SELECT
      s."firstName" key,
      UPPER(s.sex) sex,
      COUNT(DISTINCT u.id) count
    FROM users u
    JOIN
      memberships m
      ON m."userId" = u.id
    LEFT JOIN "statisticsNameSex" s
      ON SPLIT_PART(TRIM(u."firstName"), ' ', 1) = s."firstName"
    WHERE m.active = true
    GROUP BY 1, 2
    ORDER BY 3 DESC
```

There is no "coding style" for SQL statements (more like stuff we got accustomed to). I suggest to go for
- for uppercase chars if SQL it's a statement, constant or function
- drop `AS` for aliases

2021-03-02 12:20 UTC, patrickvenetz commented on packages/republik/lib/RevenueStats/segments.js
> +      date(p."createdAt") != date(ppay."createdAt") "autoPay",
```suggestion
      p."createdAt"::date != ppay."createdAt"::date "autoPay",
```

(Accustomed to casting date via `::`)

2021-03-02 12:20 UTC, patrickvenetz commented on packages/republik/lib/RevenueStats/segments.js
> +        WHEN pkg.name != 'MONTHLY_ABO' AND date(p."createdAt") != date(ppay."createdAt")
```suggestion
        WHEN pkg.name != 'MONTHLY_ABO' AND p."createdAt"::date != ppay."createdAt"::date
```

2021-03-02 12:20 UTC, patrickvenetz commented on packages/republik/lib/RevenueStats/segments.js
> +    LEFT JOIN "pledgeOptions" po ON po."pledgeId" = p.id AND date(p."createdAt") = date(ppay."createdAt")
```suggestion
    LEFT JOIN "pledgeOptions" po ON po."pledgeId" = p.id AND p."createdAt"::date = ppay."createdAt"::date
```

2021-03-02 12:20 UTC, patrickvenetz commented on packages/statistics/migrations/sqls/20210219123130-statistics-geo-country-intial-up.sql
> +  "searchNames" json,
```suggestion
  "searchNames" jsonb,
```

[As I understand `json` is parsed whenever queried while `jsonb` is stored in parsed manner and won't require "reparsing" when queried](https://www.citusdata.com/blog/2016/07/14/choosing-nosql-hstore-json-jsonb/).

2021-03-02 12:20 UTC, patrickvenetz commented on packages/statistics/migrations/sqls/20210219123130-statistics-geo-country-intial-up.sql
> +  "lon" FLOAT
```suggestion
  "lat" float,
  "lon" float
```

2021-03-02 12:20 UTC, patrickvenetz commented on packages/statistics/migrations/sqls/20210219123430-statistics-geo-postal-code-intial-up.sql
> +  "lon" FLOAT,
```suggestion
  "lat" float,
  "lon" float,
```

2021-03-02 12:20 UTC, patrickvenetz commented on packages/statistics/script/sex/importStatisticsNameSex.js
> +    await transaction.query(`TRUNCATE TABLE "statisticsNameSex"`)
(This is more of a note, [would use Pogi here](https://pogi.readthedocs.io/API/PgTable/#truncate).)

2021-03-02 14:52 UTC, fuenkchen commented on packages/republik/graphql/schema-types.js
> +  city: String
Added key and kept city as deprecated for dev convenience. Drop this once everyone is up-to-date with schema changes.

2021-03-04 12:19 UTC, fuenkchen commented on packages/republik/graphql/schema-types.js
> +  sum: Int! @deprecated(reason: "Use \`share\` instead.")
since atm we do not have a use case for the field sum, I've removed it too. I think we can easily add it if we need it in the future.

2021-03-04 13:37 UTC, fuenkchen commented on packages/republik/lib/MembershipStats/geo.js
> +  DE: (code) => code.replace(/^D[\s-]*/i, '').split(' ')[0],
Yes, right, reason is: e.g. CH does not have leading 0s, DE can have them, so we can't parseInt() german postal codes. I've added some comments and applied same methods for similar cases

2021-03-04 14:03 UTC, patrickvenetz approved these changes
LGTM!

(Added a single suggestion about a query convention.)

2021-03-04 15:21 UTC, merged